### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by michalss** [camposantogames/firewatch_localization#1]
Hi,

There is a problem with file SupportedLanguages.loc it is 0 bytes, simple empty file...

**Comment by merlinsvk** [comment]
Yep, but look into C:\Users<YourUserName>\AppData\LocalLow\CampoSanto\Firewatch\Localization ;)

**Comment by ner00** [comment]
That also happened to me, I replaced the default with the one in this fork and had to reinstall the game because I had no idea what the content was. Anyhow, this is what the default file contains:
_English|.en_us_

The content is composed by the name of the language as it appears in the settings, followed by a vertical bar, followed by the extension that the translation files have.

**Comment by michalss** [comment]
yeah that works ok NOW...

**Comment by hoverbird** [comment]
Fixed in 4a7292e, thanks for your report!
