### ISSUE TITLE
Korean shows up into XXXX

### ISSUE THREAD

**Issue by SilentMuk** [camposantogames/firewatch_localization#4]
![image](https://cloud.githubusercontent.com/assets/16540853/13384154/40dc85c0-ded6-11e5-98dc-00d3b9a88224.png)

**Comment by ner00** [comment]
Although I am not affiliated with Campo Santo, allow me to point out the following paragraph in this repository's README:

> At present, Firewatch's included fonts and layouts do not support characters outside the ISO Latin-1 set. We apologize for this limitation and hope that we will be able to remove it at some point.

Since you showed interest in joining our community translation that I have been expecting you on our Slack channel to mention this particular issue. We hope that we may be able to mod the game independently or, ideally, that Campo Santo spends a little of it's post-release effort in facilitating the usage of external fonts. 

Initially I thought that the game used common TrueType fonts but then I became aware that it's not the case, it uses textures and mappings instead which turns the issue into quite the problem for us, the modding community and translators. For this very reason I have not accepted your request to create and/or join the Korean translation team yet and won't for any unsupported charset until there is a tangible possibility of applying those translations to the game. It would be a real shame to spend days working on a translation and then not seeing it being enjoyed by anyone. My advice is that we wait patiently for an official or unofficial solution.
